#!/bin/bash

# upload files
rsync -rav --delete -e 'ssh -i ./.scaleway' \
	--exclude '.*' \
	--exclude node_modules \
	. root@vbb-telegram.jannisr.de:~/vbb-telegram/

ssh -i ./.scaleway root@vbb-telegram.jannisr.de "\
cd ~/vbb-telegram
npm i
export NODE_ENV=production
forever stop vbb-telegram
redis-cli flushdb
forever start -a --uid vbb-telegram index.js"
