version: '3'
services:
  bot:
    build: .
    depends-on:
      - redis
    links:
      - redis
    volumes:
      - .:/code
    environment:
      - TIMEZONE
      - TOKEN
    deploy:
      restart_policy:
        condition: 'on-failure'
  redis:
    image: redis:alpine
    expose:
      - '6379'
